# Generated by Django 5.0 on 2025-12-30 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(help_text='Format: A24G02 (A24=jerrycan ID, G02=group number)', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Purchase price for this jerrycan', max_digits=10)),
                ('tp_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transport Cost')),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Supplier name or location', max_length=200)),
                ('bottles_25cl', models.PositiveIntegerField(default=0)),
                ('bottles_75cl', models.PositiveIntegerField(default=0)),
                ('bottles_1L', models.PositiveIntegerField(default=0, verbose_name='Bottles 1L')),
                ('bottles_4L', models.PositiveIntegerField(default=0, verbose_name='Bottles 4L')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-supply_date', '-created_at'],
            },
        ),
    ]
