# Generated by Django 5.0 on 2026-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Purchase price for this jerrycan', max_digits=10, null=True),
        ),
    ]
